import { initReactI18next } from "react-i18next";
import i18n from "i18next";

i18n.use(initReactI18next).init({
    lng: "en",
    resources: {
        en: {
            translation: {
                SS1: 'Are you using the benefits of the Shakti scheme?',
                SS2: 'Is it easy to get a free ride on the bus?',
                SS3: 'Does the conductor issue a zero ticket every time you take a ride?',
                SS4: 'What do you use the bus service mostly for?',
                SS5: 'How often do you use the bus?',
                SS6: 'Before the scheme was launched, how did you largely commute?',
                SS7: 'What has been the benefit of free bus travel?',
                SS8: 'If you still use other modes of commute, why do you do that?',
                SS8_D: 'I am humiliated by the male passengers and conductor',
                SS8_C: 'There is no bus available on the route',
                SS8_B: 'There is too much crowd',
                SS8_A: ' Bus timings are not good',
                SS7_A: 'Cost of commute has reduced and I save money',
                SS7_B: 'I feel safer as there are more women in the bus',
                SS7_C: 'I am able to go to places that I could not go earlier',
                SS6_A: 'By bus',
                SS6_B: 'By auto/Ola/Uber',
                SS6_C: 'By two wheeler –Scooty',
                SS6_D: 'Bicycle',
                SS6_E: 'Walking',
                SS5_A: 'Daily',
                SS5_B: '2-3 times a week',
                SS5_C: 'Once a week or so',
                SS5_D: 'One a month or so',
                SS5_E: 'Rarely',
                SS4_A: 'To go to school/college/work',
                SS4_B: 'To go to the market',
                SS4_C: 'To go meet relatives',
                SS4_D: 'Others',
                SS3_A: 'Yes',
                SS3_B: 'No',
                SS2_A: 'Yes',
                SS2_B: 'No',
                SS1_A: 'Yes',
                SS1_B: 'No',
                MOBILE: "Mobile",
                MOBILE_NUMBER: "Mobile Number",
                OTP: "Otp",
                SEND_OTP: "Send Otp",
                SUBMIT: "Submit Application",
                VALIDATE_OTP: "Validate Otp",
                RESEND_OTP: "Resend Otp",
                NAME: 'Name',
                AGE: 'Age',
                SHAKHTI_HEADER: "Question related to the Shakti scheme.?"
            }
        },
        ka: {
            translation: {
                NAME: 'ಹೆಸರು',
                AGE: 'ವಯಸ್ಸು',
                MOBILE: "ಮೊಬೈಲ್",
                MOBILE_NUMBER: "ಮೊಬೈಲ್ ನಂಬರ್",
                OTP: "Otp",
                SEND_OTP: "Otp ಕಳುಹಿಸಿ",
                SHAKHTI_HEADER: "ಶಕ್ತಿ ಯೋಜನೆಗೆ ಸಂಬಂಧಿಸಿದ ಪ್ರಶ್ನೆ.?",
                SUBMIT: "ಸಲ್ಲಿಸು",
                VALIDATE_OTP: "Otp ಮೌಲ್ಯೀಕರಿಸಿ",
                RESEND_OTP: "Otp ಅನ್ನು ಮರುಕಳುಹಿಸಿ",
                SS1: "ಶಕ್ತಿ ಯೋಜನೆಯ ಅನುಕೂಲ ಪಡೆಯುತ್ತಿದ್ದೀರಾ?",
                SS1_A: "ಹೌದು",
                SS1_B: "ಇಲ್ಲ",
                SS2: "ಬಸ್ಸಿನಲ್ಲಿ ಉಚಿತ ಪ್ರಯಾಣ ಸುಲಭವೇ?",
                SS2_A: "ಹೌದು",
                SS2_B: "ಇಲ್ಲ",
                SS3: "ನೀವು ಪ್ರಯಾಣ ಮಾಡುವಾಗ ಕಂಡಕ್ಟರ್ ನಿಮಗೆ ಶೂನ್ಯ ದರದ ಟಿಕೆಟ್ ಕೊಡುತ್ತಾರೆಯೇ?",
                SS3_A: "ಹೌದು",
                SS3_B: "ಇಲ್ಲ",
                SS4: "ನೀವು ಬಸ್ ಪ್ರಯಾಣ ಮಾಡುವುದೇಕೆ?",
                SS4_A: "ಶಾಲೆ/ಕಾಲೇಜು/ಕೆಲಸಕ್ಕೆ ಹೋಗಲು",
                SS4_B: "ಮಾರುಕಟ್ಟೆಗೆ ಹೋಗಲು",
                SS4_C: "ಸಂಬಂಧಿಕರ ಮನೆಗೆ ಹೋಗಲು",
                SS4_D: "ಇತರ",
                SS5: "ನಿಮ್ಮ ಪ್ರಯಾಣದ ಪ್ರಮಾಣ?",
                SS5_A: "ಪ್ರತಿದಿನ",
                SS5_B: "ವಾರದಲ್ಲಿ 2-3ದಿನ",
                SS5_C: "ವಾರಕ್ಕೆ ಒಮ್ಮೆ",
                SS5_D: "ತಿಂಗಳಿಗೆ ಒಮ್ಮೆ",
                SS5_E: "ಅಪರೂಪಕ್ಕೊಮ್ಮೆ",
                SS6: "ಶಕ್ತಿ ಯೋಜನೆ ಜಾರಿಯಾಗುವ ಮುನ್ನ ನೀವು ಹೇಗೆ ಪ್ರಯಾಣಿಸುತ್ತಿದ್ದೀರಿ?",
                SS6_A: "ಬಸ್ಸಿನಲ್ಲಿ",
                SS6_B: "ಆಟೋರಿಕ್ಷಾ",
                SS6_C: "ದ್ವಿಚಕ್ರ ವಾಹನ-ಸ್ಕೂಟಿ",
                SS6_D: "ಸೈಕಲ್",
                SS6_E: "ನಡಿಗೆ",
                SS7: "ಉಚಿತ ಬಸ್ ಪ್ರಯಾಣದ ಅನುಕೂಲಗಳೇನು?",
                SS7_A: "ಪ್ರಯಾಣದ ಖರ್ಚು ಕಡಿಮೆಯಾಗಿದೆ. ನನಗೆ ಹಣ ಉಳಿತಾಯವಾಗುತ್ತಿದೆ",
                SS7_B: "ಹೆಚ್ಚು ಮಹಿಳೆಯರೇ ಇರುವುದರಿಂದ ಬಸ್ ಸುರಕ್ಷಿತ ಅನ್ನಿಸುತ್ತದೆ.",
                SS7_C: "ಈ ಹಿಂದೆ ಹೋಗಲು ಸಾಧ್ಯವಿಲ್ಲದ ಊರುಗಳಿಗೆ ಈಗ ಹೋಗುತ್ತಿದ್ದೇನೆ.",
                SS8: "ಉಚಿತ ಬಸ್ ಇದ್ದರೂ ಆಟೋ ಕಾರ್ ಮುಂತಾದುವುಗಳನ್ನೇಕೆ ಬಳಸುತ್ತೀರಿ?",
                SS8_A: "ಸಮಯಕ್ಕೆ ಸರಿಯಾಗಿ ಬಸ್ ಇರುವುದಿಲ್ಲ",
                SS8_B: "ಅತಿಯಾದ ಜನಜಂಗುಳಿ",
                SS8_C: "ನಾನು ಹೋಗುವ ದಾರಿಯಲ್ಲಿ ಬಸ್ ಇಲ್ಲ",
                SS8_D: "ಗಂಡಸರು ಮತ್ತು ಕಂಡಕ್ಟರ್‌ಗಳು ಕೀಳಾಗಿ ನಡೆಸಿಕೊಳ್ಳುತ್ತಾರೆ",
            }
        },
    },
    keySeparator: false,
    interpolation: { escapeValue: false }
});

export default i18n;
